@startuml
class TBL_POST {
    +POST_ID: int
    +DATE_HOURS: datetime
    +USER_ID: int
    +TITLE: string
}

class TBL_POST_DETAIL {
    +POST_DETAIL_ID: int
    +CONTENT: text
    +FOTO: string
    +POST_ID: int
}

TBL_POST "1" --> "1" TBL_POST_DETAIL : contém um detalhamento de post
@enduml
